spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cloud_comment}
    username: ${SPRING_DATASOURCE_USERNAME:cloud_comment}
    password: ${SPRING_DATASOURCE_PASSWORD:cloud_comment}
